image: golang:latest

stages:
  - test
  - release

variables:
  GOLANGCI_LINT_VERSION: "v1.35.2"

test:
  stage: test
  before_script:
    - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin ${GOLANGCI_LINT_VERSION}
    - golangci-lint --version
  script:
    - golangci-lint run

release:
  stage: release
  script:
    - go get -u github.com/mailru/easyjson/easyjson@v0.7.0
    - curl -sL https://git.io/goreleaser | bash
  only:
    - tags
