stages:
  - test
  - release

variables:
  GOLANGCI_LINT_VERSION: v1.21.0
  GORELEASER_IMAGE: goreleaser/goreleaser:latest

test:
  image: golang:alpine
  stage: test
  before_script:
    - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin ${GOLANGCI_LINT_VERSION}
    - golangci-lint --version
  script:
    - golangci-lint run

release:
  image: docker:stable
  services:
    - docker:dind
  stage: release
  script:
    - docker pull ${GORELEASER_IMAGE}
    - docker run --rm --privileged -v $PWD:/go/src/gitlab.com/${CI_PROJECT_NAMESPACE} -v /var/run/docker.sock:/var/run/docker.sock -w /go/src/github.com/${CI_PROJECT_NAMESPACE} -e GITLAB_TOKEN $GORELEASER_IMAGE release --rm-dist
  only:
    - tags
